name: dotnet-core

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out triton repository
        uses: actions/checkout@v2
      - name: Set up .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Run tests (with code coverage)
        run: >
          dotnet test -f netcoreapp3.1 -c Release tests/Triton.Tests/Triton.Tests.csproj
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover
          /p:ExcludeByAttribute=GeneratedCodeAttribute
      - name: Upload code coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/Triton.Tests/coverage.opencover.xml
      - name: Build artifacts
        run: |
          dotnet publish -c Debug src/Triton/Triton.csproj
          dotnet publish -c Release src/Triton/Triton.csproj
      - name: Publish artifacts (${{matrix.os }} Debug)
        uses: actions/upload-artifact@v2
        with:
          name: Triton (${{matrix.os }} Debug)
          path: src/Triton/bin/Debug/netstandard2.0/publish
      - name: Publish artifacts (${{matrix.os }} Release)
        uses: actions/upload-artifact@v2
        with:
          name: Orion.Core (${{matrix.os }} Release)
          path: src/Triton/bin/Release/netstandard2.0/publish
